fix(release): wheel requires libwayland-server0 installed
ImportError: libwayland-server.so.0: cannot open shared object file: No such file or directory